#!/bin/bash
############################
blue='\033[1;34m'
black='\033[1;30m'
red='\033[1;31m'
green='\033[1;32m'
yellow='\033[1;33m'
magenta='\033[1;35m'
cyan='\033[1;36m'
lgray='\033[1;37m'
dgray='\033[1;90m'
white='\033[1;97m'
bgred='\033[1;41m'
bggreen='\033[1;42m'
bgblue='\033[1;44m'
bgmagenta='\033[1;45m'
bgcyan='\033[1;46m'
bgwhite='\033[1;107m'
reset='\033[0m'
############################
calc_bar()
{
	pcent_avail=$1
	pcent_occup=$(( 100 - $pcent_avail ))
	bar_length=$2
	used_length=$(( $bar_length * $pcent_occup / 100 ))	
	printf "["
	for ((i=1; i<=$used_length; i++)); do
		printf "${green}="
	done
	for ((i=1; i<=$(( $bar_length - $used_length )); i++)); do
		printf "${reset}."
	done
	printf "]"
}
############################